version: '3.8'

services:
  hydron:
    build:
      context: ./apps/hydron
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - supabase

  hellfire:
    build:
      context: ./apps/hellfire
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - supabase

  supabase:
    image: supabase/supabase-docker:latest
    ports:
      - "54321:54321"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  supabase-data: